In [35]:
import pandas as pd
import numpy as np

In [36]:
import matplotlib.pyplot as plt
import psycopg2
import getpass

In [37]:
%matplotlib inline
plt.style.use('ggplot')

In [38]:
# Create a database connection
user = 'postgres'
password = 'master'
host = 'localhost'
dbname = 'mimic'
schema = 'mimiciii'

In [39]:
# Connect to the database
con = psycopg2.connect(dbname=dbname, user=user, host=host, 
                       password=password)
cur = con.cursor()
cur.execute('SET search_path to {}'.format(schema))

In [40]:
# Get length of stay from the icustays table
query = \
"""
select first_careunit, los
from mimiciii.icustays i 
"""

data = pd.read_sql_query(query,con)

In [41]:
# Display the first few rows of the data
data.head(100)

   first_careunit      los
0            MICU   3.2490
1            MICU   3.2788
2             CCU   2.8939
3            MICU   2.0600
4             CCU   1.6202
5            MICU   1.4862
6            MICU   8.8143
7             CCU   7.1314
8             CCU   1.3378
9            NICU   0.7313
10           MICU   4.0658
11           NICU  13.9504
12           MICU   7.7389
13          TSICU   0.8519
14           MICU  30.6932
15           SICU   4.9051
16           MICU   1.0685
17          TSICU  28.6880
18           MICU  54.8469
19           SICU   1.8310
20           SICU   2.9940
21           SICU   3.1830
22           NICU   8.1027
23          TSICU   4.6738
24            CCU   0.5102
25            CCU   1.4023
26           MICU   0.8276
27           MICU   0.8854
28           CSRU   1.0570
29            CCU   2.5609
..            ...      ...
70           MICU   3.6877
71           MICU   0.8932
72            CCU   5.0078
73            CCU   2.4448
74           MICU   3.0680
75           SICU   9.9866
76           NICU   0.6965
77           NICU   0.2939
78            CCU   2.3419
79           NICU  14.3065
80           SICU   1.9713
81           NICU   0.0433
82           NICU   0.1559
83           MICU   1.1439
84           MICU  31.7018
85           SICU   1.5153
86           SICU   5.3010
87          TSICU  17.0983
88           NICU   0.1119
89           MICU   2.2438
90           MICU   3.4836
91           MICU   3.8119
92            CCU   4.9684
93           MICU   4.8545
94           CSRU   3.2045
95           SICU   0.8653
96           NICU   0.0691
97           CSRU   3.0389
98           MICU   3.8597
99           MICU   0.9677

[100 rows x 2 columns]

In [42]:
data['los_median'] = data.groupby('first_careunit')['los'].median()
data.head(50)

   first_careunit      los  los_median
0            MICU   3.2490         NaN
1            MICU   3.2788         NaN
2             CCU   2.8939         NaN
3            MICU   2.0600         NaN
4             CCU   1.6202         NaN
5            MICU   1.4862         NaN
6            MICU   8.8143         NaN
7             CCU   7.1314         NaN
8             CCU   1.3378         NaN
9            NICU   0.7313         NaN
10           MICU   4.0658         NaN
11           NICU  13.9504         NaN
12           MICU   7.7389         NaN
13          TSICU   0.8519         NaN
14           MICU  30.6932         NaN
15           SICU   4.9051         NaN
16           MICU   1.0685         NaN
17          TSICU  28.6880         NaN
18           MICU  54.8469         NaN
19           SICU   1.8310         NaN
20           SICU   2.9940         NaN
21           SICU   3.1830         NaN
22           NICU   8.1027         NaN
23          TSICU   4.6738         NaN
24            CCU   0.5102         NaN
25            CCU   1.4023         NaN
26           MICU   0.8276         NaN
27           MICU   0.8854         NaN
28           CSRU   1.0570         NaN
29            CCU   2.5609         NaN
30           SICU   0.9057         NaN
31           CSRU   0.8618         NaN
32           NICU   0.0904         NaN
33           MICU   2.2590         NaN
34           NICU   0.0501         NaN
35           NICU   0.2220         NaN
36            CCU   2.4159         NaN
37           MICU   1.8447         NaN
38           CSRU   1.0917         NaN
39           SICU   2.7756         NaN
40            CCU   0.5129         NaN
41            CCU   3.9185         NaN
42           CSRU   4.9438         NaN
43           MICU   0.7925         NaN
44           MICU   5.8118         NaN
45           SICU   2.4370         NaN
46          TSICU   2.7815         NaN
47           SICU   5.9133         NaN
48           MICU   1.0615         NaN
49            CCU  26.1535         NaN

In [43]:
data.set_index('first_careunit').plot.barh(y='median_los', figsize=(5, 5), color='blue')

KeyError: 'median_los'

In [ ]:
sizes = np.array(data.median_los)

def absolute_value(val):
    a  = np.round(val/100.*sizes.sum(), 0)
    return a

plot = data.plot.pie(y='median_los', figsize=(5, 5), legend=False, labels=data.first_careunit, autopct=absolute_value)