In [19]:
import pandas as pd

In [20]:
import matplotlib.pyplot as plt
import psycopg2
import getpass

In [21]:
%matplotlib inline
plt.style.use('ggplot')

In [22]:
# Create a database connection
user = 'postgres'
password = 'master'
host = 'localhost'
dbname = 'mimic'
schema = 'mimiciii'

In [23]:
# Connect to the database
con = psycopg2.connect(dbname=dbname, user=user, host=host, 
                       password=password)
cur = con.cursor()
cur.execute('SET search_path to {}'.format(schema))

In [24]:
# Get length of stay from the icustays table
query = \
"""
select diagnosis, l.subject_id, label, value, valueuom 
from mimiciii.labevents l inner join d_labitems dl on
l.itemid = dl.itemid inner join admissions a on
a.subject_id = l.subject_id
limit 100
"""

data = pd.read_sql_query(query,con)

In [25]:
# Display the first few rows of the data
data.head(1500)

,diagnosis,subject_id,label,value,valueuom
0,HYPOTENSION,3,SPECIMEN TYPE,ART,None
1,HYPOTENSION,3,SPECIMEN TYPE,ART,None
2,HYPOTENSION,3,SPECIMEN TYPE,ART,None
3,HYPOTENSION,3,SPECIMEN TYPE,ART,None
4,HYPOTENSION,3,SPECIMEN TYPE,ART,None
5,HYPOTENSION,3,SPECIMEN TYPE,ART,None
6,HYPOTENSION,3,SPECIMEN TYPE,MIX,None
7,HYPOTENSION,3,SPECIMEN TYPE,ART,None
8,HYPOTENSION,3,SPECIMEN TYPE,ART,None
9,HYPOTENSION,3,SPECIMEN TYPE,MIX,None
10,HYPOTENSION,3,SPECIMEN TYPE,ART,None
11,HYPOTENSION,3,SPECIMEN TYPE,ART,None
12,HYPOTENSION,3,SPECIMEN TYPE,MIX,None
13,HYPOTENSION,3,SPECIMEN TYPE,ART,None
14,HYPOTENSION,3,SPECIMEN TYPE,MIX,None
15,HYPOTENSION,3,SPECIMEN TYPE,ART,None
16,HYPOTENSION,3,SPECIMEN TYPE,ART,None
17,HYPOTENSION,3,SPECIMEN TYPE,ART,None
18,HYPOTENSION,3,SPECIMEN TYPE,ART,None
19,HYPOTENSION,3,SPECIMEN TYPE,ART,None
20,HYPOTENSION,3,SPECIMEN TYPE,MIX,None
21,HYPOTENSION,3,SPECIMEN TYPE,ART,None
22,HYPOTENSION,3,SPECIMEN TYPE,ART,None
23,HYPOTENSION,3,SPECIMEN TYPE,ART,None
24,HYPOTENSION,3,SPECIMEN TYPE,ART,None
25,HYPOTENSION,3,SPECIMEN TYPE,ART,None
26,HYPOTENSION,3,SPECIMEN TYPE,ART,None
27,HYPOTENSION,3,SPECIMEN TYPE,ART,None
28,HYPOTENSION,3,SPECIMEN TYPE,ART,None
29,"FEVER,DEHYDRATION,FAILURE TO THRIVE",4,SPECIMEN TYPE,MIX,None
...,...,...,...,...,...
70,HEMORRHAGIC CVA,9,SPECIMEN TYPE,ART,None
71,HEMORRHAGIC CVA,9,SPECIMEN TYPE,ART,None
72,HEMORRHAGIC CVA,9,SPECIMEN TYPE,ART,None
73,HEMORRHAGIC CVA,9,SPECIMEN TYPE,ART,None
74,HEMORRHAGIC CVA,9,SPECIMEN TYPE,ART,None
75,PATIENT FORAMEN OVALE\ PATENT FORAMEN OVALE MI...,17,SPECIMEN TYPE,ART,None
76,PERICARDIAL EFFUSION,17,SPECIMEN TYPE,ART,None
77,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,ART,None
78,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,ART,None
79,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,ART,None
80,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,ART,None
81,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,ART,None
82,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,ART,None
83,CORONARY ARTERY DISEASE,13,SPECIMEN TYPE,ART,None
84,CORONARY ARTERY DISEASE,13,SPECIMEN TYPE,ART,None
85,CORONARY ARTERY DISEASE,13,SPECIMEN TYPE,ART,None
86,CORONARY ARTERY DISEASE,13,SPECIMEN TYPE,ART,None
87,CORONARY ARTERY DISEASE,13,SPECIMEN TYPE,ART,None
88,CORONARY ARTERY DISEASE,13,SPECIMEN TYPE,ART,None
89,CORONARY ARTERY DISEASE,13,SPECIMEN TYPE,ART,None
90,CORONARY ARTERY DISEASE,13,SPECIMEN TYPE,ART,None
91,CORONARY ARTERY DISEASE,13,SPECIMEN TYPE,ART,None
92,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,ART,None
93,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,ART,None
94,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,ART,None
95,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,VEN,None
96,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,ART,None
97,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,ART,None
98,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,ART,None
99,PANCREATIC CANCER/SDA,12,SPECIMEN TYPE,ART,None

In [26]:
# Compute nissing values in each column
data.isnull().mean().sort_values(ascending=False)*100
#avg_los = data.los.median()
#print(avg_los)

valueuom      100.0
value           0.0
label           0.0
subject_id      0.0
diagnosis       0.0
dtype: float64

In [27]:
# Plot the distribution

#diagnoses = data.groupby(['diagnosis', 'count']).diagnosis.count().plot.barh()

#diagnoses = data.groupby(['diagnosis', 'count']).diagnosis.count().plot.pie()